[Match]
Architecture=x86-64

[Distribution]
Architecture=x86-64

[Content]
Packages=
	amd64-microcode
	intel-microcode
	linux-image-generic
	systemd-boot
	systemd-boot-efi

Bootloader=systemd-boot

KernelCommandLine=console=ttyS0 rd.emergency=poweroff transparent_hugepage=madvise
