# Copyright 2025 s3rj1k
# SPDX-License-Identifier: MIT

heat_template_version: 2021-04-16

description: Template for lab VM

parameters:
  prefix:
    type: string
    description: "Resource name prefix"
    label: "Resource name prefix"
    constraints:
      - length:
          min: 1
          max: 32
        description: "Resource name prefix must be between 1 and 32 characters"
      - allowed_pattern: "^[a-zA-Z0-9-_]+$"
        description: "Resource name prefix can only contain letters, numbers, underscore and hyphen"

  registry_mirror:
    type: string
    description: "Image registry mirror URL"
    label: "Image Registry Mirror"
    default: ""

  install_libvirt:
    type: boolean
    description: "Install libvirt and related tools"
    label: "Install Libvirt"
    default: true

  sushy_hacks:
    type: boolean
    description: "Enable sushy-tools workarounds for boot order management"
    label: "Enable Sushy Hacks"
    default: false

  install_zot:
    type: boolean
    description: "Install Zot container registry"
    label: "Install Zot Registry"
    default: true

  install_kite:
    type: boolean
    description: "Install Kite Kubernetes dashboard"
    label: "Install Kite"
    default: true

  traefik_hcp_mode:
    type: boolean
    description: "Configure Traefik for HCP (Hosted Control Plane)"
    label: "Traefik HCP Mode"
    default: false

  cilium_lb_enabled:
    type: boolean
    description: "Enable Cilium LoadBalancer (L2 announcements, kube-proxy replacement)"
    label: "Cilium LB Enabled"
    default: true

  image_id:
    type: string
    description: "Image to use for the instances."
    default: ubuntu-24.04-minimal-cloudimg-amd64
    label: "Server Image"
    constraints:
      - allowed_values:
          - ubuntu-24.04-minimal-cloudimg-amd64
          - debian-13-generic-amd64
        description: "Must be a known Image ID"

  ssh_pub_key:
    type: string
    description: "SSH public key for instance access"
    label: "SSH Public Key"
    constraints:
      - length:
          min: 1

  external_network:
    type: string
    description: "External network for router gateway"
    default: "public"
    label: "External Network"

  network_cidr:
    type: string
    description: "CIDR for the network"
    default: "10.42.71.0/24"
    label: "Network CIDR"

  allocation_pool_start:
    type: string
    description: "Start of IP allocation pool"
    default: "10.42.71.200"
    label: "Allocation Pool Start"

  allocation_pool_stop:
    type: string
    description: "End of IP allocation pool"
    default: "10.42.71.250"
    label: "Allocation Pool Stop"

  vm_ip_1:
    type: string
    description: "First IP address for VM"
    default: "10.42.71.101"
    label: "VM IP 1"

  lb_ip:
    type: string
    description: "IP address for Cilium LoadBalancer (Traefik)"
    default: "10.42.71.102"
    label: "LB IP"

  availability_zone:
    type: string
    description: "Availability zone for instances"
    default: "nova"
    label: "Availability Zone"

  flavor:
    type: string
    description: "Instance flavor"
    default: "re.jenkins.master.xlarge"
    label: "Instance Flavor"

  volume_size:
    type: number
    description: "Size of root volume in GB"
    default: 200
    label: "Volume Size"

resources:
  ssh_authorized_keys:
    type: "OS::Heat::Value"
    properties:
      value:
        - { get_param: ssh_pub_key }

  network:
    type: "OS::Neutron::Net"
    properties:
      name:
        str_replace:
          template: $prefix-network
          params:
            $prefix:
              get_param: prefix
      port_security_enabled: false
      admin_state_up: true
      availability_zone_hints:
        - get_param: availability_zone

  subnet:
    type: "OS::Neutron::Subnet"
    properties:
      name:
        str_replace:
          template: $prefix-subnet
          params:
            $prefix:
              get_param: prefix
      network_id:
        get_resource: network
      cidr:
        get_param: network_cidr
      ip_version: 4
      enable_dhcp: true
      allocation_pools:
        - start:
            get_param: allocation_pool_start
          end:
            get_param: allocation_pool_stop

  router:
    type: "OS::Neutron::Router"
    properties:
      name:
        str_replace:
          template: $prefix-router
          params:
            $prefix:
              get_param: prefix
      admin_state_up: true
      external_gateway_info:
        network:
          get_param: external_network

  router_interface:
    type: "OS::Neutron::RouterInterface"
    properties:
      router_id:
        get_resource: router
      subnet_id:
        get_resource: subnet

  port_vm_1:
    type: "OS::Neutron::Port"
    properties:
      name:
        str_replace:
          template: $prefix-port-vm-1
          params:
            $prefix:
              get_param: prefix
      network:
        get_resource: network
      admin_state_up: true
      port_security_enabled: false
      fixed_ips:
        - subnet:
            get_resource: subnet
          ip_address:
            get_param: vm_ip_1

  port_lb:
    type: "OS::Neutron::Port"
    properties:
      name:
        str_replace:
          template: $prefix-port-lb
          params:
            $prefix:
              get_param: prefix
      network:
        get_resource: network
      admin_state_up: true
      port_security_enabled: false
      fixed_ips:
        - subnet:
            get_resource: subnet
          ip_address:
            get_param: lb_ip

  floating_ip_vm_1:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network:
        get_param: external_network
      port_id:
        get_resource: port_vm_1

  floating_ip_lb:
    type: "OS::Neutron::FloatingIP"
    properties:
      floating_network:
        get_param: external_network
      port_id:
        get_resource: port_lb

  vm_wait_handle:
    type: "OS::Heat::WaitConditionHandle"

  vm_wait_condition:
    type: "OS::Heat::WaitCondition"
    properties:
      handle:
        get_resource: vm_wait_handle
      timeout: 3600

  vm_user_data:
    type: "OS::Heat::Value"
    properties:
      value:
        str_replace:
          template: |
            #cloud-config

            # https://cloudinit.readthedocs.io/en/24.1/reference/examples.html
            # Logs are in:
            #  - /var/log/cloud-init.log
            #  - /var/log/cloud-init-output.log

            users:
              - name: root
                shell: /bin/bash
                lock_passwd: false
                plain_text_passwd: root
                ssh_authorized_keys: %ssh_keys%
              - name: user
                shell: /bin/bash
                lock_passwd: true
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh_authorized_keys: %ssh_keys%

            # https://cloudinit.readthedocs.io/en/latest/reference/modules.html#ansible

            runcmd:
              - |
                apt-get update && apt-get install -y ansible git || true

                KITE_EXTRA_ARGS=""
                if [ "%install_kite%" = "True" ]; then
                  KITE_EXTRA_ARGS='-e {"KITE_HOSTNAMES":["%vm_floating_ip%.nip.io","%lb_floating_ip%.nip.io"]}'
                fi

                ansible-pull -U "https://github.com/s3rj1k/playground.git" \
                  playbooks/lab.yml \
                  -v \
                  -e "REGISTRY_MIRROR='%registry_mirror%'" \
                  -e "INSTALL_LIBVIRT=%install_libvirt%" \
                  -e "SUSHY_HACKS=%sushy_hacks%" \
                  -e "INSTALL_ZOT=%install_zot%" \
                  -e "INSTALL_KITE=%install_kite%" \
                  -e "TRAEFIK_HCP_MODE=%traefik_hcp_mode%" \
                  -e "CILIUM_LB_ENABLED=%cilium_lb_enabled%" \
                  -e "LB_IP_RANGE_START=%lb_ip%" \
                  -e "LB_IP_RANGE_STOP=%lb_ip%" \
                  $KITE_EXTRA_ARGS
                ANSIBLE_RESULT=$?

                if [ $ANSIBLE_RESULT -eq 0 ]; then
                  %wc_notify% --data-binary "{\"status\": \"SUCCESS\", \"data\": \"Ansible playbook execution completed\"}"
                else
                  %wc_notify% --data-binary "{\"status\": \"FAILURE\", \"reason\": \"Ansible playbook execution failed\"}"
                  exit 1
                fi
          params:
            "%ssh_keys%":
              get_attr:
                - ssh_authorized_keys
                - value
            "%registry_mirror%":
              get_param: registry_mirror
            "%install_libvirt%":
              get_param: install_libvirt
            "%sushy_hacks%":
              get_param: sushy_hacks
            "%install_zot%":
              get_param: install_zot
            "%install_kite%":
              get_param: install_kite
            "%traefik_hcp_mode%":
              get_param: traefik_hcp_mode
            "%cilium_lb_enabled%":
              get_param: cilium_lb_enabled
            "%lb_ip%":
              get_param: lb_ip
            "%lb_floating_ip%":
              get_attr:
                - floating_ip_lb
                - floating_ip_address
            "%vm_floating_ip%":
              get_attr:
                - floating_ip_vm_1
                - floating_ip_address
            "%wc_notify%":
              get_attr:
                - vm_wait_handle
                - curl_cli

  vm:
    type: "OS::Nova::Server"
    properties:
      name:
        str_replace:
          template: "%prefix%-vm"
          params:
            "%prefix%":
              get_param: prefix
      availability_zone:
        get_param: availability_zone
      flavor:
        get_param: flavor
      config_drive: true
      block_device_mapping_v2:
        - image_id:
            get_param: image_id
          delete_on_termination: true
          boot_index: 0
          volume_size:
            get_param: volume_size
      networks:
        - port:
            get_resource: port_vm_1
      user_data_format: RAW
      user_data:
        get_attr:
          - vm_user_data
          - value

outputs:
  vm_floating_ip_1:
    description: Floating IP address for VM (SSH, kube-apiserver)
    value:
      get_attr:
        - floating_ip_vm_1
        - floating_ip_address

  lb_floating_ip:
    description: Floating IP address for LoadBalancer (Traefik, HCP)
    value:
      get_attr:
        - floating_ip_lb
        - floating_ip_address

  vm_user_data:
    description: Rendered VM user-data
    value:
      get_attr:
        - vm_user_data
        - value
