[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=noble
Repositories=main,universe

[Build]
WithNetwork=yes

[Content]
CleanPackageMetadata=no

Hostname=ct
Keymap=us
Locale=C
Timezone=UTC

WithDocs=no
WithRecommends=no

Packages=
	apt
	apt-transport-https
	ca-certificates
	curl
	ebtables
	gnupg
	iproute2
	iptables
	iputils-ping
	jq
	kubeadm
	kubectl
	kubelet
	libpam-systemd
	locales
	nano
	procps
	systemd
	systemd-resolved
	systemd-timesyncd

RemovePackages=
	libnss-resolve

Bootable=no

[Validation]
Checksum=yes
