[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk
Output=disk.vm

[Build]
WithNetwork=yes
SandboxTrees=mkosi.sandbox

[Content]
CleanPackageMetadata=no

Hostname=vm
Keymap=us
Locale=C
Timezone=UTC

WithDocs=no
WithRecommends=no

Packages=
	apt
	apt-transport-https
	bash
	btrfs-progs
	ca-certificates
	cloud-guest-utils
	cloud-init
	cloud-initramfs-growroot
	curl
	dbus-broker
	diffutils
	e2fsprogs
	ebtables
	gawk
	git
	git-lfs
	gnupg
	grep
	gzip
	hwloc-nox
	iproute2
	iptables
	iputils-ping
	jq
	kmod
	less
	libpam-systemd
	linux-firmware
	linux-perf
	locales
	login
	multipath-tools
	nano
	nftables
	openssh-server
	pciutils
	polkitd
	qemu-guest-agent
	sed
	shim-signed
	socat
	ssh
	ssh-import-id
	strace
	sudo
	systemd
	systemd-coredump
	systemd-resolved
	systemd-sysv
	systemd-timesyncd
	tar
	tzdata
	udev
	unattended-upgrades
	vim
	zstd

RemovePackages=
	libnss-resolve

# [ -d /sys/firmware/efi ] && echo UEFI || echo BIOS
Bootable=yes

[Validation]
Checksum=yes

[Runtime]
CPUs=2
RAM=6G
VSock=yes
RuntimeSize=50G
QemuArgs=-nographic
