name: Docker Image Builder (mkosi)

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-docker-mkosi.yaml"
      - "vms/efi/mkosi/debian/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MKOSI_IMAGE: debian-trixie

jobs:
  build-and-push:
    strategy:
      matrix:
        include:
          - arch: amd64
            mkosi_arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            mkosi_arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup ORAS
        uses: oras-project/setup-oras@v2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install pipx
        run: pip install pipx pefile

      - name: Install mkosi
        run: |
          sudo pip install git+https://github.com/systemd/mkosi.git
          mkosi --version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            debian-archive-keyring \
            mtools \
            python3-pefile \
            systemd-boot

      - name: Build OS Image
        shell: bash
        working-directory: vms/efi/mkosi/debian
        run: |
          sudo mkosi --force --profile docker --architecture=${{ matrix.mkosi_arch }} \
            --tools-tree=default \
            --tools-tree-distribution=debian \
            --tools-tree-release=trixie \
            build
          sudo chmod 0666 disk.vm.raw

          gzip --keep disk.vm.raw

          echo "ARTIFACT_TAG=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Log in to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        shell: bash
        working-directory: vms/efi/mkosi/debian
        run: |
          oras version

          export DIGEST="$(sha256sum disk.vm.raw.gz | awk '{print $1}')"
          export TIMESTAMP="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          mkdir -p image-builder/images/capi/output/ && \
            mv -v disk.vm.raw.gz image-builder/images/capi/output/${{ env.MKOSI_IMAGE }}-docker-${{ env.ARTIFACT_TAG }}-${{ matrix.arch }}.gz

          oras push ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.MKOSI_IMAGE }}-docker:${{ env.ARTIFACT_TAG }}-${{ matrix.arch }}.gz \
            --annotation "org.opencontainers.image.authors=${{ github.actor }}" \
            --annotation "org.opencontainers.image.created=${TIMESTAMP}" \
            --annotation "org.opencontainers.image.title=${{ env.MKOSI_IMAGE }}-docker" \
            --annotation "org.opencontainers.image.version=${{ env.ARTIFACT_TAG }}" \
            --annotation "org.opencontainers.image.revision=${{ github.sha }}" \
            --annotation "org.opencontainers.image.base.digest=${DIGEST}" \
            --artifact-type application/vnd.acme.rocket.config image-builder/images/capi/output/${{ env.MKOSI_IMAGE }}-docker-${{ env.ARTIFACT_TAG }}-${{ matrix.arch }}.gz

      - name: Write summary
        shell: bash
        working-directory: vms/efi/mkosi/debian
        run: |
          echo "## Image pull using ORAS" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "oras pull ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.MKOSI_IMAGE }}-docker:${{ env.ARTIFACT_TAG }}-${{ matrix.arch }}.gz" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
